apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loco-app-ingress
  namespace: loco
  annotations:
    spec.ingressClassName: nginx
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loco-app-service
            port:
              number: 80
