apiVersion: v1
kind: Service
metadata:
  name: loco-app-service
spec:
  selector:
    app: loco-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
